name: Docker Base Image Builds

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    name: BuildDockerImage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      
      - if: startsWith(github.ref, 'refs/heads/master')
        run: echo "TAG=latest" >> $GITHUB_ENV
        
      - if: startsWith(github.ref, 'refs/tags')
        run: echo "TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}
         